# Generated by Django 3.1.1 on 2020-10-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='digital',
            new_name='complete',
        ),
    ]
